### ISSUE TITLE
Can't remove node

### ISSUE THREAD

**Issue by Climberdav** [patternfly/patternfly-bootstrap-treeview#25]
Hello, 

If I try to remove a node with this `$('#tree').treeview('removeNode', [ '0.0.3.3' ]);` it fire this error : 
`bootstrap-treeview.min.js:1 Uncaught TypeError: Cannot read property 'remove' of undefined
    at g._removeNodeEl (http://localhost/cours2/web/assets/vendor/patternfly-bootstrap-treeview/dist/bootstrap-treeview.min.js:1:16323)
    at g.<anonymous> (http://localhost/cours2/web/assets/vendor/patternfly-bootstrap-treeview/dist/bootstrap-treeview.min.js:1:21255)
    at String.f (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:3698)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:2861)
    at g.removeNode (http://localhost/cours2/web/assets/vendor/patternfly-bootstrap-treeview/dist/bootstrap-treeview.min.js:1:21152)
    at Object.f [as removeNode] (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:3698)
    at HTMLDivElement.<anonymous> (http://localhost/cours2/web/assets/vendor/patternfly-bootstrap-treeview/dist/bootstrap-treeview.min.js:1:26758)
    at Function.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:2861)
    at n.fn.init.each (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js:2:845)
    at n.fn.init.a.fn.(anonymous function) [as treeview] (http://localhost/cours2/web/assets/vendor/patternfly-bootstrap-treeview/dist/bootstrap-treeview.min.js:1:26626)`

**Comment by 3xxx** [comment]
my practice here:
http://blog.csdn.net/hotqin888/article/details/54798737

**Comment by guoguolq** [comment]
Uncaught TypeError: node.remove is not a function

**Comment by skateman** [comment]
@Climberdav could you please post a fiddle where it is reproducible?

**Comment by Deca** [comment]
Same error here, someone found a solution?
