### ISSUE TITLE
addNode error

### ISSUE THREAD

**Issue by renanyoy** [patternfly/patternfly-bootstrap-treeview#79]
addNode returns
`TypeError: Cannot read property 'visible' of undefined
bootstrap-treeview.js:606
    at Tree._setVisible (/Volumes/ssd/git/a2ds/server/office/public/libs/treeview/dist/bootstrap-treeview.js:606:40)
    at Tree.<anonymous> (/Volumes/ssd/git/a2ds/server/office/public/libs/treeview/dist/bootstrap-treeview.js:572:12)
    at Object.e (/Volumes/ssd/git/a2ds/server/office/public/assets/lib/jquery/jquery.min.js:2:3556)
    at Function.each (/Volumes/ssd/git/a2ds/server/office/public/assets/lib/jquery/jquery.min.js:2:2716)
    at Tree._setExpanded (/Volumes/ssd/git/a2ds/server/office/public/libs/treeview/dist/bootstrap-treeview.js:571:8)
    at Tree.<anonymous> (/Volumes/ssd/git/a2ds/server/office/public/libs/treeview/dist/bootstrap-treeview.js:1343:12)
    at Array.e (/Volumes/ssd/git/a2ds/server/office/public/assets/lib/jquery/jquery.min.js:2:3556)
    at i (/Volumes/ssd/git/a2ds/server/office/public/assets/lib/jquery/jquery.min.js:2:28018)
`

**Comment by renanyoy** [comment]
new node is just {text:"label"}

**Comment by renanyoy** [comment]
jquery: 3.2.1
bootstrap 4.0.0

**Comment by skateman** [comment]
The library doesn't support bootstrap 4 and for now there's no plan to do so.

https://github.com/patternfly/patternfly-bootstrap-treeview/issues/78

**Comment by renanyoy** [comment]
can you point me a bootstrap 4.0 treeview library, please ?

**Comment by skateman** [comment]
Sorry, but I have no information about such library.

**Comment by renanyoy** [comment]
ok, thanks
maybe you could add an alert on the readme that the library isn't compatible with bootstrap 4.0
because for now it's just  "works with bootstrap >= 3.0.0"
